FROM php:5.6-apache

RUN usermod -u 1000 www-data && chown www-data: /var/www/html -R
RUN apt-get update \
        && apt-get install -y libmcrypt-dev \
                libjpeg62-turbo-dev \
                libpng-dev \
                libfreetype6-dev \
                libxml2-dev \
                libcurl4-openssl-dev \
                libicu-dev \
                mysql-client \
                wget \
                subversion \
                git \
                curl \
                ca-certificates \
                libcurl3 \
                tar \
                openssh-client \
                unzip \
                sendmail \
                locales \
                vim \
                # gpg \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install iconv intl gettext opcache pdo mysqli pdo_mysql mbstring soap gd exif zip curl calendar

    # Possible values for ext-name:
    # bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zend_test zip

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i -e 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

COPY php.ini /usr/local/etc/php/
RUN a2enmod rewrite
WORKDIR /tmp
RUN curl -s https://getcomposer.org/installer | php \
        && mv /tmp/composer.phar /usr/local/bin/composer && chmod a+x /usr/local/bin/composer
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && chmod +x /usr/local/bin/wp
WORKDIR /var/www/html
